version : "3.9"
services:
   pair-finder-db:
     image: postgres
     restart: always
     container_name: pair-finder-db
     ports:
      - 5432:5432
     environment:
       POSTGRES_PASSWORD: roshan
       PGDATA: /data/postgres
     volumes:
       - postgres:/data/postgres

volumes:
  postgres: